name: ximdex
home: http://www.ximdex.com/
version: 0.0.1
description: CMS  tools for simultaneous management of data and content through services such as intelligent search engines.
maintainers:
  - Juan Manuel Torres <juanmanuel.torres@aventurabinaria.es>
details:
  Ximdex is a CMS written using PHP and Java. Ximdex provides tools for simultaneous management of data and content through services such as intelligent search engines, concept recommendation, information aggregators, editors, image and text recognition, analysis and visualization.
