apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-wp
  labels:
    provider: mysql-wp
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mysql-wp
    spec:
      containers:
      - name: mysql-wp
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
