apiVersion: v1
kind: Service
metadata:
  name: mysql-wp
  labels:
    provider: mysql-wp
    heritage: helm
spec:
  clusterIP: 10.254.200.20
  ports:
  - port: 3306
  selector:
    provider: mysql-wp
