apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    provider: mysql
    heritage: helm
spec:
  clusterIP: 10.254.200.20
  ports:
  - port: 3306
  selector:
    provider: mysql
----
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
    heritage: helm
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: wordpress
