apiVersion: v1
kind: ReplicationController
metadata:
  name: wordpress
  labels:
    app: wordpress
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
