apiVersion: v1
kind: Service
metadata:
  name: mysql-ximdex
  labels:
    provider: mysql-ximdex
    heritage: helm
spec:
  clusterIP: 10.254.200.30
  ports:
  - port: 3306
  selector:
    provider: mysql-ximdex
