apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-ximdex
  labels:
    provider: mysql-ximdex
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mysql-ximdex
    spec:
      containers:
      - name: mysql-ximdex
        image: mysql:5.6
        env:
        - name: "MYSQL_USER"
          value: "mysql"
        - name: "MYSQL_PASSWORD"
          value: "mysql"
        - name: "MYSQL_DATABASE"
          value: "ximdex"
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
