apiVersion: v1
kind: ReplicationController
metadata:
  name: ximdex
  labels:
    app: ximdex
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ximdex
    spec:
      containers:
      - name: ximdex
        image: ximdex/ximdex
        ports:
        - containerPort: 80
        env:
          - name: XIMDEX_DB_USER
            value: root
          - name: XIMDEX_DB_PASSWORD
            value: root
          - name: XIMDEX_DB_HOST
            value: 10.254.200.30:3306
          - name: XIMDEX_DB_NAME
            value: ximdex
