apiVersion: v1
kind: Service
metadata:
  name: ximdex
  labels:
    app: ximdex
    heritage: helm
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: ximdex
